#!/fh/fast/subramaniam_a/user/rasi/virtualenv/default/bin/python
# -*- coding: utf-8 -*-
'''Convert XML files generated by Tecan plate reader to CSV
usage: python xml2csv_plate_reader.py xmlfilename
'''
import xml.etree.ElementTree as ET
import pandas as pd

File = sys.argv[1]

tree = ET.parse(File)
root = tree.getroot()
# Tecan XML files start with this root tag
if root.tag != 'MeasurementResultData':
    print "File is not in the right format."
    raise
# Get time of measurement and do not look at microsecond data
timestamp = pd.to_datetime(root.attrib['Date']).replace(microsecond=0)

data = dict()
# each section is a distinct type of measurement: od, yfp etc.
for section in root.iter('Section'):
    measurement = section.attrib['Name']
    data[measurement] = dict()
    params = [param.attrib for param in section.iter('Parameters')]
    # iterate over all wells for this measurement
    for well in section.iter('Well'):
        wellid = well.attrib['Pos']
        data[measurement][wellid] = float(well.find('Single').text)

data = pd.DataFrame(data)
data.index.name = 'well'
data['time'] = timestamp
data.to_csv(timestamp.strftime('%Y%m%d_%Hh%Mm%Ss') + '.tsv', sep='\t')
